name: ztdl
channels:
- defaults
- jasonb857
- bitsort
- sunpy
- HCC
dependencies:
- python=3.8.*
- bz2file==0.98
- cython==0.29.*
- pip==23.0.*
- numpy==1.19.*
- jupyter==1.0.*
- matplotlib==3.4.*
- setuptools==52.0.*
- scikit-learn==0.24.*
- scipy==1.6.*
- pandas==1.2.*
- pillow==8.2.*
- seaborn==0.11.*
- pytest==6.2.*
- twisted==21.2.*
- pip:
  - tensorflow==2.13.*
